scrape_configs:
  - job_name: 'sample_monitoring'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8080']
        labels:
          application: 'Prod'