{
 "title": "Ad Platform",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "User amount",
   "type": "timeseries",
   "description": "Amount of users and advertisers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "client_amount", "legendFormat": "Client amount" },
    { "expr": "advertiser_amount", "legendFormat": "Advertiser amount" }
   ]
  },
  {
   "title": "Campaign Amount",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "campaign_amount_active", "legendFormat": "Active Campaigns" },
    { "expr": "campaign_amount", "legendFormat": "All Campaigns" },
    {
     "expr": "(campaign_amount_active / clamp_min(campaign_amount, 1) * 100) * clamp_max(campaign_amount, 1)",
     "legendFormat": "Active Percentage"
    }
   ]
  },
  {
   "title": "Ad Requests Per Day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "ad_request_counter_total", "legendFormat": "Всего запросов" },
    { "expr": "ad_unavailable_counter_total", "legendFormat": "Запросы не получившие рекламу" },
    {
     "expr": "ad_repeat_counter_total",
     "legendFormat": "Requests that were fulfilled through previously shown advertisements"
    },
    {
     "expr": "ad_impression_counter_total",
     "legendFormat": "Запросы, которым успешно была показана реклама"
    }
   ]
  },
  {
   "title": "General Ad Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (ad_impression_counter_total)",
     "legendFormat": "Impressions"
    },
    { "expr": "sum (ad_click_counter_total)", "legendFormat": "Clicks" },
    {
     "expr": "((sum (ad_click_counter_total)) / clamp_min((sum (ad_impression_counter_total)), 1) * 100) * clamp_max((sum (ad_impression_counter_total)), 1)",
     "legendFormat": "Conversion"
    }
   ]
  },
  {
   "title": "Ad Revenue",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ad_impression_revenue_counter_total+ad_click_revenue_counter_total",
     "legendFormat": "Запросы, которым успешно была показана реклама"
    },
    {
     "expr": "ad_impression_revenue_counter_total",
     "legendFormat": "Всего запросов"
    },
    { "expr": "ad_click_revenue_counter_total", "legendFormat": "Запросы не получившие рекламу" }
   ]
  }
 ]
}